version: "3.3"

services:
  server:
    container_name: steamTools-server
    build:
      context: ./server/
    restart: always
    ports:
      - 3230:3230

  client:
    container_name: steamTools-client
    build:
      context: ./client/
    restart: always
    ports:
      - 3200:80
